branches:
  only: 
    - master

matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode12
      script:
        # macOS
        - xcodebuild clean -project "Mach-Swift.xcodeproj" 
        - xcodebuild test -project "Mach-Swift.xcodeproj" -scheme "Mach-Swift-macOS" -destination "platform=OS X" -configuration Debug

        # iOS
        - xcodebuild clean -project "Mach-Swift.xcodeproj" 
        - xcodebuild test -project "Mach-Swift.xcodeproj" -scheme "Mach-Swift-iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11 Pro Max" -configuration Debug
